echo boot sector compiling...
nasm src/boot/boot_sect.asm -f bin -o build/boot/boot_sect.bin

echo kernel-entry compiling...
nasm src/boot/kernel-entry.asm -f elf64 -o build/boot/kernel-entry.o

echo kernel compiling...
gcc -ffreestanding -c src/kernel/kernel.c -o build/kernel/kernel.o

echo linking kernel with kernel-entry...
ld -o build/kernel/kernel.bin -Ttext 0x1000 build/boot/kernel-entry.o build/kernel/kernel.o --oformat binary

echo merging bootloader and kernel...
cat build/boot/boot_sect.bin build/kernel/kernel.bin > build/os-image

echo build finished!
